services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "app.log"
    profiles: ["only_app", "apm"]
  fluentd:
    build: 
      context: ./fluentd
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    profiles: ["apm"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    ports:
      - "9200:9200"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "elasticsearch.log"
    profiles: ["apm"]
  elasticsearch-exporter:
    image: prometheuscommunity/elasticsearch-exporter
    command:
      - '--es.uri=http://elasticsearch:9200'
    ports:
      - "9114:9114"
    depends_on:
      - elasticsearch
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "elasticsearch-exporter.log"
    profiles: ["apm"]
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "kibana.log"
    profiles: ["apm"]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "prometheus.log"
    profiles: ["apm"]
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    depends_on:
      - prometheus
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "grafana.log"
    profiles: ["apm"]
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "14268:14268"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: "jaeger.log"
    profiles: ["apm"]
  
