spring.mvc.hiddenmethod.filter.enabled=true
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.exporter.jaeger.endpoint=http://jaeger:14268/api/traces