apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  ports:
    - port: 80
      targetPort: web
  selector:
    app: {{ .Release.Name }}-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: {{ .Release.Name }}-database